### ISSUE TITLE
XML-RPC API no longer supported on Maventa side

### ISSUE THREAD

**Issue by thejhh** [nnarhinen/node-maventa#5]
```

/---------------------------------- Error -----------------------------------\
| Error: Invalid XML-RPC message
+---------------------------------- stack -----------------------------------+
|     at Deserializer.onDone (/home/jheusala/scripts/enterpriser/node_modules/node-maventa/node_modules/xmlrpc/lib/deserializer.js:79:21)
|     at SAXStream.emit (events.js:92:17)
|     at Object.SAXStream._parser.onend (/home/jheusala/scripts/enterpriser/node_modules/node-maventa/node_modules/xmlrpc/node_modules/sax/lib/sax.js:171:8)
|     at emit (/home/jheusala/scripts/enterpriser/node_modules/node-maventa/node_modules/xmlrpc/node_modules/sax/lib/sax.js:325:33)
|     at end (/home/jheusala/scripts/enterpriser/node_modules/node-maventa/node_modules/xmlrpc/node_modules/sax/lib/sax.js:363:3)
|     at Object.SAXParser.end (/home/jheusala/scripts/enterpriser/node_modules/node-maventa/node_modules/xmlrpc/node_modules/sax/lib/sax.js:137:24)
|     at SAXStream.end (/home/jheusala/scripts/enterpriser/node_modules/node-maventa/node_modules/xmlrpc/node_modules/sax/lib/sax.js:209:16)
|     at IncomingMessage.onend (_stream_readable.js:502:10)
|     at IncomingMessage.g (events.js:180:16)
|     at IncomingMessage.emit (events.js:117:20)
\----------------------------------------------------------------------------/
```

I started getting this error some time ago. Has Maventa updated their API or something?

**Update:** Maventa has dropped support for XML-RPC API and therefor for this module as well

**Comment by thejhh** [comment]
This API is using Maventa's API end point `/apis/denver/api` and I don't see it exists anymore... nor find any documentation for it.

It seems to exist in here though https://secure.maventa.com/apis/v1.1/wsdl/

**Comment by thejhh** [comment]
Updating dependencies didn't affect the error.

**Comment by thejhh** [comment]
Maventa's API is responsing with 400 Bad Request for request of `invoice_list_inbound_between_dates`. No more information.

**Comment by thejhh** [comment]
I wonder if this is because of missing properties:

```xml
<xsd:complexType name="ApiKeys">
<xsd:all>
<xsd:element name="user_api_key" type="xsd:string"/>
<xsd:element name="vendor_api_key" type="xsd:string"/>
<xsd:element name="company_uuid" type="xsd:string"/>
<xsd:element name="license_key" type="xsd:string" minOccurs="0"/>
<xsd:element name="license_meta" type="xsd:string" minOccurs="0"/>
</xsd:all>
</xsd:complexType>
```

The library only has `user_api_key`, `vendor_api_key` and `company_uuid`. 

It's missing `license_key` and `license_meta`.

**Comment by thejhh** [comment]
I guess those two should be optional, so it doesn't explain this.
 
 https://documentation.maventa.com/integration-guide//#api-keys

**Comment by thejhh** [comment]
I don't see anywhere in the Maventa documentation anything about XML-RPC API. The request is in XML-RPC format though, not SOAP XML message...

**Comment by thejhh** [comment]
I guess Maventa has dropped the XML-RPC API support. I have contacted their support to get verification about this.

Would probably need to start migrating to REST API, e.g. https://documentation.maventa.com/rest-api/#invoice-receiving

**Comment by thejhh** [comment]
Maventa support confirmed that XML-RPC API is no longer available, so this module is no longer supported on the Maventa side. It would need to be rewritten to use REST or SOAP API.
